name: Cron Job

on:
    workflow_dispatch:
    schedule:
        - cron: "59 03 * * *"

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: cargo build --verbose
            - name: Run
              env:
                  TOKEN: ${{ secrets.TOKEN }}
                  CHANNELS: ${{ secrets.CHANNELS }}
              run: cargo run --verbose
